#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
# ufw allow 'Nginx HTTP'
# ufw allow ssh
# ufw allow 'OpenSSH'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
service nginx restart
