#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/error/404.html
replace_string="\t#error_page 404 \/404.html;"
string_error="\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"
sed -i "s/$replace_string/$string_error/" /etc/nginx/sites-available/default
service nginx restart
