#!/usr/bin/env bash
#Ubuntu container’s Nginx installation from listening on port 80
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/defaul
service nginx restart
kill -SIGKILL "$(cat /var/run/nginx.pid)"
