#!/usr/bin/env bash
# This script displays cript that configures an Ubuntu server with requirements.
# Requirements:
#localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
sed -i "/127.0.0.2/c\127.0.0.1" ~/hosts.new
sed -i "2i8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
