#!/usr/bin/env bash
# script
pkill apache2
sed -i "s/'#user www-data;'/'user nginx;'/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
